quadrantChart
    title Ease of Use and Flexibility of Animation Libraries
    x-axis Less Flexible --> More Flexible
    y-axis Hard to Use --> Easy to Use
    quadrant-1 Overkill
    quadrant-2 Ideal
    quadrant-3 Basic
    quadrant-4 Complex
    "Manim Community Edition": [0.7, 0.3]
    "Processing": [0.6, 0.5]
    "Unity": [0.9, 0.2]
    "Godot": [0.8, 0.2]
    "p5.js": [0.5, 0.6]
    "Our Target Product": [0.6, 0.7]
